version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ../locust/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://apifunkyfoo.graemefoster.net/ --loglevel DEBUG
  
  worker:
    image: locustio/locust
    volumes:
      - ../locust/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master --loglevel DEBUG
